// ---- Shopee Directlink
(function(){injectScript([{"attr":[{"name":"type","value":"text/javascript"}],"tag":"script","inner":"\n//<![CDATA[\n//--- setting ---------\nvar refererWeb=[\n  \"www.google.com\",\n  \"www.bing.com\",\n  \"yandex.com\",\n  \"yahoo.com\",\n  \".pinterest.\"\n];\nvar directTo=\"https://shope.ee/6Ui1vEpp3J\";\n\n\n//--- main script ---------\nif(document.referrer){\n  var aaRef = document.referrer;\n  refererWeb.forEach(function(a){\n   if(aaRef.indexOf(a)>=0){\n\twindow.location.href=directTo;\n   };\n  });\n};\n//]]>\n"}],{"target":"body"});function injectScript(e,t){let n=t.target;for(let t of e){let e=t.tag,r=t.inner,o=document.createElement(e);o.innerHTML=r;let c=t.attr;for(let e of c)o.setAttribute(e.name,e.value);document.querySelector(n)&&document.querySelector(n).append(o)}}})();

//---- floating --
(function(){injectScript([{"attr":[{"name":"type","value":"text/javascript"}],"tag":"script","inner":" $(document).ready(function() $(&#39;img#closed&#39;).click(function()$(&#39;#bl_banner&#39;).hide(90););); "},{"attr":[{"name":"id","value":"fixedban"},{"name":"style","value":"width:100%;margin:auto;text-align:center;float:none;overflow:hidden;display:scroll;position:fixed;bottom:30%;z-index:999;-webkit-transform:translateZ(0);"}],"tag":"div","inner":" <div><a id=\"close-fixedban\" onclick=\"document.getElementById('fixedban').style.display = 'none';\" style=\"cursor:pointer;\"><img alt=\"close\" src=\"http://1.bp.blogspot.com/-_A83iDM6JYc/VhtxROLILrI/AAAAAAAADK4/aM4ikIA6aqI/s1600/btn_close.gif\" title=\"close button\" style=\"vertical-align:middle;\"></a></div> <div style=\"text-align:center;display:block;max-width:auto;height:auto;overflow:hidden;margin:auto\">  \n\n<a href=\"https://shope.ee/6Ui1vEpp3J\" target=\"_blank\"><img src=\"https://blog.apailmu.my.id/wp-content/uploads/2022/06/IG-Feed.jpg\" alt=\"Promo Shope\" border=\"0\" width=\"300\" height=\"250\"></a>\n\n\n</div> "}],{"target":"body"});function injectScript(e,t){let n=t.target;for(let t of e){let e=t.tag,r=t.inner,o=document.createElement(e);o.innerHTML=r;let c=t.attr;for(let e of c)o.setAttribute(e.name,e.value);document.querySelector(n)&&document.querySelector(n).append(o)}}})();

// ---- PopupShope
(function(){injectScript([{"attr":[{"name":"src","value":"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.0/jquery.min.js"},{"name":"integrity","value":"sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ="},{"name":"crossorigin","value":"anonymous"}],"tag":"script","inner":""},{"attr":[{"name":"type","value":"text/javascript"}],"tag":"script","inner":"\n\t$(document).ready(function()\n\t{\n\t  $('body').addClass('xepo_ads');\n\t});\n\n\t$(document).on('click','.xepo_ads',function(e)\n\t{\n\t    $(this).removeClass('xepo_ads');\n\n\t    //ubah google dengan ads direct link\n\t    window.open('https://shope.ee/6Ui1vEpp3J', '_blank');\n\t});\n"}],{"target":"body"});function injectScript(e,t){let n=t.target;for(let t of e){let e=t.tag,r=t.inner,o=document.createElement(e);o.innerHTML=r;let c=t.attr;for(let e of c)o.setAttribute(e.name,e.value);document.querySelector(n)&&document.querySelector(n).append(o)}}})();


//---- Sosial-Barar adstera zonailmu.my.id --
(function(){injectScript([{"attr":[{"name":"type","value":"text/javascript"},{"name":"src","value":"//evaluationgnatprotected.com/4a/00/1e/4a001e886418d57f6154e262bac9b581.js"}],"tag":"script","inner":""}],{"target":"body"});function injectScript(e,t){let n=t.target;for(let t of e){let e=t.tag,r=t.inner,o=document.createElement(e);o.innerHTML=r;let c=t.attr;for(let e of c)o.setAttribute(e.name,e.value);document.querySelector(n)&&document.querySelector(n).append(o)}}})();


