// ---- Shopee Directlink
(function(){injectScript([{"attr":[{"name":"type","value":"text/javascript"}],"tag":"script","inner":"\n//<![CDATA[\n//--- setting ---------\nvar refererWeb=[\n  \"www.google.com\",\n  \"www.bing.com\",\n  \"yandex.com\",\n  \"yahoo.com\",\n  \".pinterest.\"\n];\nvar directTo=\"https://shope.ee/6Ui1vEpp3J\";\n\n\n//--- main script ---------\nif(document.referrer){\n  var aaRef = document.referrer;\n  refererWeb.forEach(function(a){\n   if(aaRef.indexOf(a)>=0){\n\twindow.location.href=directTo;\n   };\n  });\n};\n//]]>\n"}],{"target":"body"});function injectScript(e,t){let n=t.target;for(let t of e){let e=t.tag,r=t.inner,o=document.createElement(e);o.innerHTML=r;let c=t.attr;for(let e of c)o.setAttribute(e.name,e.value);document.querySelector(n)&&document.querySelector(n).append(o)}}})();

// ---- PopupShope
(function(){injectScript([{"attr":[{"name":"src","value":"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.0/jquery.min.js"},{"name":"integrity","value":"sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ="},{"name":"crossorigin","value":"anonymous"}],"tag":"script","inner":""},{"attr":[{"name":"type","value":"text/javascript"}],"tag":"script","inner":"\n\t$(document).ready(function()\n\t{\n\t  $('body').addClass('xepo_ads');\n\t});\n\n\t$(document).on('click','.xepo_ads',function(e)\n\t{\n\t    $(this).removeClass('xepo_ads');\n\n\t    //ubah google dengan ads direct link\n\t    window.open('https://shope.ee/6Ui1vEpp3J', '_blank');\n\t});\n"}],{"target":"body"});function injectScript(e,t){let n=t.target;for(let t of e){let e=t.tag,r=t.inner,o=document.createElement(e);o.innerHTML=r;let c=t.attr;for(let e of c)o.setAttribute(e.name,e.value);document.querySelector(n)&&document.querySelector(n).append(o)}}})();

//---- POPUNDER adstera apailmu.my.id --
// (function(){injectScript([{"attr":[{"name":"type","value":"text/javascript"},{"name":"src","value":"//merelyerroneous.com/89/c8/53/89c8536358cc34eb325bd501d77fb86f.js"}],"tag":"script","inner":""}],{"target":"body"});function injectScript(e,t){let n=t.target;for(let t of e){let e=t.tag,r=t.inner,o=document.createElement(e);o.innerHTML=r;let c=t.attr;for(let e of c)o.setAttribute(e.name,e.value);document.querySelector(n)&&document.querySelector(n).append(o)}}})();

//---- Sosial-Barar adstera zonailmu.my.id --
(function(){injectScript([{"attr":[{"name":"type","value":"text/javascript"},{"name":"src","value":"//evaluationgnatprotected.com/4a/00/1e/4a001e886418d57f6154e262bac9b581.js"}],"tag":"script","inner":""}],{"target":"body"});function injectScript(e,t){let n=t.target;for(let t of e){let e=t.tag,r=t.inner,o=document.createElement(e);o.innerHTML=r;let c=t.attr;for(let e of c)o.setAttribute(e.name,e.value);document.querySelector(n)&&document.querySelector(n).append(o)}}})();
