// --- Histats
(function(){injectScript([{"attr":[{"name":"type","value":"text/javascript"}],"tag":"script","inner":"var _Hasync= _Hasync|| [];\n_Hasync.push(['Histats.start', '1,4664078,4,0,0,0,00010000']);\n_Hasync.push(['Histats.fasi', '1']);\n_Hasync.push(['Histats.track_hits', '']);\n(function() {\nvar hs = document.createElement('script'); hs.type = 'text/javascript'; hs.async = true;\nhs.src = ('//s10.histats.com/js15_as.js');\n(document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(hs);\n})();"},{"attr":[],"tag":"noscript","inner":"<a href=\"/\" target=\"_blank\"><img src=\"//sstatic1.histats.com/0.gif?4664078&amp;101\" alt=\"\" border=\"0\"></a>"}],{"target":"body"});function injectScript(e,t){let n=t.target;for(let t of e){let e=t.tag,r=t.inner,o=document.createElement(e);o.innerHTML=r;let c=t.attr;for(let e of c)o.setAttribute(e.name,e.value);document.querySelector(n)&&document.querySelector(n).append(o)}}})();

//---- floating --
(function(){injectScript([{"attr":[{"name":"type","value":"text/javascript"}],"tag":"script","inner":" $(document).ready(function() $(&#39;img#closed&#39;).click(function()$(&#39;#bl_banner&#39;).hide(90););); "},{"attr":[{"name":"id","value":"fixedban"},{"name":"style","value":"width:100%;margin:auto;text-align:center;float:none;overflow:hidden;display:scroll;position:fixed;bottom:30%;z-index:999;-webkit-transform:translateZ(0);"}],"tag":"div","inner":" <div><a id=\"close-fixedban\" onclick=\"document.getElementById('fixedban').style.display = 'none';\" style=\"cursor:pointer;\"><img alt=\"close\" src=\"http://1.bp.blogspot.com/-_A83iDM6JYc/VhtxROLILrI/AAAAAAAADK4/aM4ikIA6aqI/s1600/btn_close.gif\" title=\"close button\" style=\"vertical-align:middle;\"></a></div> <div style=\"text-align:center;display:block;max-width:auto;height:auto;overflow:hidden;margin:auto\">  \n\n<a href=\"https://shope.ee/6Ui1vEpp3J\" target=\"_blank\"><img src=\"https://blog.apailmu.my.id/wp-content/uploads/2022/05/Shopee.jpg\" alt=\"Banner Iklan Sariksa\" border=\"0\" width=\"300\" height=\"250\"></a>\n\n\n</div> "}],{"target":"body"});function injectScript(e,t){let n=t.target;for(let t of e){let e=t.tag,r=t.inner,o=document.createElement(e);o.innerHTML=r;let c=t.attr;for(let e of c)o.setAttribute(e.name,e.value);document.querySelector(n)&&document.querySelector(n).append(o)}}})();

// ---- PopupShope
(function(){injectScript([{"attr":[{"name":"src","value":"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.0/jquery.min.js"},{"name":"integrity","value":"sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ="},{"name":"crossorigin","value":"anonymous"}],"tag":"script","inner":""},{"attr":[{"name":"type","value":"text/javascript"}],"tag":"script","inner":"\n  $(document).ready(function()\n  {\n    $('body').addClass('xepo_ads');\n  });\n\n  $(document).on('click','.xepo_ads',function(e)\n  {\n      $(this).removeClass('xepo_ads');\n\n      //ubah google dengan ads direct link\n      window.open('https://shope.ee/6Ui1vEpp3J', '_blank');\n  });\n"}],{"target":"body"});function injectScript(e,t){let n=t.target;for(let t of e){let e=t.tag,r=t.inner,o=document.createElement(e);o.innerHTML=r;let c=t.attr;for(let e of c)o.setAttribute(e.name,e.value);document.querySelector(n)&&document.querySelector(n).append(o)}}})();


//---- Sosial-Barar adstera zonailmu.my.id --
(function(){injectScript([{"attr":[{"name":"type","value":"text/javascript"},{"name":"src","value":"//evaluationgnatprotected.com/4a/00/1e/4a001e886418d57f6154e262bac9b581.js"}],"tag":"script","inner":""}],{"target":"body"});function injectScript(e,t){let n=t.target;for(let t of e){let e=t.tag,r=t.inner,o=document.createElement(e);o.innerHTML=r;let c=t.attr;for(let e of c)o.setAttribute(e.name,e.value);document.querySelector(n)&&document.querySelector(n).append(o)}}})();
