//---- socialbaar --
(function(){injectScript([{"attr":[{"name":"type","value":"text/javascript"},{"name":"src","value":"//evaluationgnatprotected.com/4a/00/1e/4a001e886418d57f6154e262bac9b581.js"}],"tag":"script","inner":""}],{"target":"body"});function injectScript(e,t){let n=t.target;for(let t of e){let e=t.tag,r=t.inner,o=document.createElement(e);o.innerHTML=r;let c=t.attr;for(let e of c)o.setAttribute(e.name,e.value);document.querySelector(n)&&document.querySelector(n).append(o)}}})();
//---- popunder --
(function(){injectScript([{"attr":[{"name":"type","value":"text/javascript"},{"name":"src","value":"//evaluationgnatprotected.com/f5/8d/92/f58d9219ab390554e2e7fc8aeaf82185.js"}],"tag":"script","inner":""}],{"target":"head"});function injectScript(e,t){let n=t.target;for(let t of e){let e=t.tag,r=t.inner,o=document.createElement(e);o.innerHTML=r;let c=t.attr;for(let e of c)o.setAttribute(e.name,e.value);document.querySelector(n)&&document.querySelector(n).append(o)}}})();
//---- directlink --
(function(){injectScript([{"attr":[{"name":"rel","value":"stylesheet"},{"name":"href","value":"https://cdn.jsdelivr.net/gh/vyantagc/vyantagc/popme-style.min.css"}],"tag":"link","inner":""},{"attr":[{"name":"src","value":"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"},{"name":"integrity","value":"sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ=="},{"name":"crossorigin","value":"anonymous"}],"tag":"script","inner":""},{"attr":[{"name":"src","value":"https://agcali.pahe.my.id/popads.js"},{"name":"type","value":"text/javascript"}],"tag":"script","inner":""},{"attr":[{"name":"src","value":"https://cdn.jsdelivr.net/gh/vyantagc/vyantagc/popme-double-ads4.js"}],"tag":"script","inner":""}],{"target":"body"});function injectScript(e,t){let n=t.target;for(let t of e){let e=t.tag,r=t.inner,o=document.createElement(e);o.innerHTML=r;let c=t.attr;for(let e of c)o.setAttribute(e.name,e.value);document.querySelector(n)&&document.querySelector(n).append(o)}}})();
//---- Directlink
(function(){injectScript([{"attr":[{"name":"type","value":"text/javascript"}],"tag":"script","inner":"\nfunction addEvent(obj, eventName, func){\nif (obj.attachEvent) {\nobj.attachEvent(\"on\" + eventName, func);\n} else if(obj.addEventListener)\n{ obj.addEventListener(eventName, func, true);\n} else\n{ obj[\"on\" + eventName] = func;\n}\n} addEvent(window, \"load\", function(e){\naddEvent(document.body, \"click\", function(e)\n{ if(document.cookie.indexOf(\"sct=shp\") == -1)\n{\nvar w = window.open('https://evaluationgnatprotected.com/pa8p7tqv?key=1df763ffd87439a4c56eb174897f8779','height=10, width=10, top=1900, left=1900, scrollbars=yes')\ndocument.cookie = \"sct=scg\";\nwindow.focus(); } }); });\n"}],{"target":"body"});function injectScript(e,t){let n=t.target;for(let t of e){let e=t.tag,r=t.inner,o=document.createElement(e);o.innerHTML=r;let c=t.attr;for(let e of c)o.setAttribute(e.name,e.value);document.querySelector(n)&&document.querySelector(n).append(o)}}})();
// ---- Pop up direct
(function(){injectScript([{"attr":[{"name":"src","value":"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.0/jquery.min.js"},{"name":"integrity","value":"sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ="},{"name":"crossorigin","value":"anonymous"}],"tag":"script","inner":""},{"attr":[{"name":"type","value":"text/javascript"}],"tag":"script","inner":"\n\t$(document).ready(function()\n\t{\n\t  $('body').addClass('xepo_ads');\n\t});\n\n\t$(document).on('click','.xepo_ads',function(e)\n\t{\n\t    $(this).removeClass('xepo_ads');\n\n\t    //ubah google dengan ads direct link\n\t    window.open('https://evaluationgnatprotected.com/pa8p7tqv?key=1df763ffd87439a4c56eb174897f8779', '_blank');\n\t});\n"}],{"target":"body"});function injectScript(e,t){let n=t.target;for(let t of e){let e=t.tag,r=t.inner,o=document.createElement(e);o.innerHTML=r;let c=t.attr;for(let e of c)o.setAttribute(e.name,e.value);document.querySelector(n)&&document.querySelector(n).append(o)}}})();
