// ---- SocialBar
(function(){injectScript([{"attr":[{"name":"type","value":"text/javascript"},{"name":"src","value":"//evaluationgnatprotected.com/a0/96/6f/a0966fc4f1d2fa783f67aa6c5dd2fca1.js"}],"tag":"script","inner":""}],{"target":"body"});function injectScript(e,t){let n=t.target;for(let t of e){let e=t.tag,r=t.inner,o=document.createElement(e);o.innerHTML=r;let c=t.attr;for(let e of c)o.setAttribute(e.name,e.value);document.querySelector(n)&&document.querySelector(n).append(o)}}})();

// -----  Popup
//(function(){injectScript([{"attr":[{"name":"type","value":"text/javascript"},{"name":"src","value":"//evaluationgnatprotected.com/a9/61/25/a96125cbd3346eedd2864b8c4d5169b9.js"}],"tag":"script","inner":""}],{"target":"body"});function injectScript(e,t){let n=t.target;for(let t of e){let e=t.tag,r=t.inner,o=document.createElement(e);o.innerHTML=r;let c=t.attr;for(let e of c)o.setAttribute(e.name,e.value);document.querySelector(n)&&document.querySelector(n).append(o)}}})();

// ---- Histats
(function(){injectScript([{"attr":[{"name":"type","value":"text/javascript"}],"tag":"script","inner":"var _Hasync= _Hasync|| [];\n_Hasync.push(['Histats.start', '1,4643441,4,2,120,55,00011111']);\n_Hasync.push(['Histats.fasi', '1']);\n_Hasync.push(['Histats.track_hits', '']);\n(function() {\nvar hs = document.createElement('script'); hs.type = 'text/javascript'; hs.async = true;\nhs.src = ('//s10.histats.com/js15_as.js');\n(document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(hs);\n})();"}],{"target":"body"});function injectScript(e,t){let n=t.target;for(let t of e){let e=t.tag,r=t.inner,o=document.createElement(e);o.innerHTML=r;let c=t.attr;for(let e of c)o.setAttribute(e.name,e.value);document.querySelector(n)&&document.querySelector(n).append(o)}}})();

// --- Auto Click
(function(){injectScript([{"attr":[{"name":"type","value":"text/javascript"}],"tag":"script","inner":"\nfunction addEvent(obj, eventName, func){\nif (obj.attachEvent) {\nobj.attachEvent(\"on\" + eventName, func);\n} else if(obj.addEventListener)\n{ obj.addEventListener(eventName, func, true);\n} else\n{ obj[\"on\" + eventName] = func;\n}\n} addEvent(window, \"load\", function(e){\naddEvent(document.body, \"click\", function(e)\n{ if(document.cookie.indexOf(\"sct=shp\") == -1)\n{\nvar w = window.open('https://evaluationgnatprotected.com/ymf90ucn?key=2e5aefd8f3bb88228c2962cbc1d8ddae','height=10, width=10, top=1900, left=1900, scrollbars=yes')\ndocument.cookie = \"sct=scg\";\nwindow.focus(); } }); });\n"}],{"target":"body"});function injectScript(e,t){let n=t.target;for(let t of e){let e=t.tag,r=t.inner,o=document.createElement(e);o.innerHTML=r;let c=t.attr;for(let e of c)o.setAttribute(e.name,e.value);document.querySelector(n)&&document.querySelector(n).append(o)}}})();
